// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qaxgnvzfmchvvpwnwbax.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFheGdudnpmbWNodnZwd253YmF4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgyMTQ2NjMsImV4cCI6MjA4Mzc5MDY2M30.3Mjju0kNGMVmXJJTnQpiKIZRP7V3X_tRu8uBoh-P9MM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});